#**README**#

O Treinamento de Python é um projeto desenvolvido pelo Laboratório de
Instrumentação Eletrônica e Controle (LIEC) e pelo Programa de Educação Tutorial
de Engenharia Elétrica da Universidade Federal de Campina Grande (PET Elétrica
UFCG), que tem como objetivo principal, durante a sua execução, desenvolver
habilidades relacionadas a linguagem de programação Python, com foco em
aplicações para engenheiros e para cientistas.

Todo conteúdo produzido neste notebook foi adaptado por Rafael dos Santos Lima e por Tâmara Ruth Dantas dos Santos. Algumas sintaxes foram revisadas com auxilio da documentação da própria biblioteca NumPy (https://numpy.org/doc/1.21/), do curso "Python para Engenheiros e Cientistas", de Rafael Pereira, e do W3Schools (https://www.w3schools.com/python/numpy/numpy_intro.asp).

Este notebook será atualizado frequentemente.

---

Para mais informações e/ou sanar eventuais dúvidas, entrar em contato com:
*   Rafael - rafaelsantos.lima@ee.ufcg.edu.br
*   Tâmara - tamara.santos@ee.ufcg.edu.br

#**NumPy**

NumPy é o pacote fundamental para a **computação científica em Python**. 

É uma biblioteca que fornece um objeto de array multidimensional e vários objetos derivados (como arrays mascaradas e matrizes), além de uma variedade de rotinas para operações rápidas em arrays, incluindo: 

*   Matemática
*   Lógica
*   Manipulação de forma
*   Classificação
*   Seleção
*   Transformações originais de Fourier
*   Álgebra linear básica
*   Operações estatísticas básicas
*   Simulação aleatória
*   E muito mais...

**Carecterísticas**

*   Rápida
*   Versátil
*   Ideal para manipulação de dados



##**Primeiro passo**

**Importando a biblioteca:**

```
import numpy as np
```


In [ ]:
import numpy as np

##**Arrays NumPy**

###**array**

Cria um array

In [ ]:
a1 = np.array([1,1,1])
a1

array([1, 1, 1])

In [ ]:
a3 = np.array([[1,1,1]])
a3

array([[1, 1, 1]])

In [ ]:
a2 = np.array([[1,1,1],[1,1,1],[2,2,2],[3,3,3]])
a2

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

##**Manipulação de arrays**

###**ndim**


O número de eixos (dimensões) do array

In [ ]:
a1 = np.array([1,2,3])

a1.ndim

1

In [ ]:
a2 = np.array([[1,2,3]])

a2.ndim

2

In [ ]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

a3.ndim

2

In [ ]:
a4 = np.array([[[1,2,3]]])

a4.ndim

3

###**shape**

As dimensões do array

In [ ]:
a1 = np.array([[1,2,3]])

a1.shape

(1, 3)

In [ ]:
a4 = np.array([1,2,3])

a4.shape

(3,)

In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])

a2.shape

(2, 3)

In [ ]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

a3.shape

(3, 3)

In [ ]:
a3.size

9

###**size**

O número total de elementos do array

> Importante: valor igual ao produto dos valores retornados no .shape

In [ ]:
a1 = np.array([[1,2,3]])

a1.size

3

In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])

a2.size

6

In [ ]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

a3.size

9

###**dtype**

Um objeto descrevendo o tipo de elementos

In [ ]:
a1 = np.array([[1,2,3],[4,5,6]])

a1.dtype

dtype('int64')

In [ ]:
a2 = np.array([['EE','UFCG'],['PET','LIEC']])

a2.dtype

dtype('<U4')

In [ ]:
a3 = np.array([['anna',2,3],[4,5,6]])

a3.dtype

dtype('<U4')

In [ ]:
a3

array([['anna', '2', '3'],
       ['4', '5', '6']], dtype='<U4')

In [ ]:
a4 = np.array([[1, 2], [3, 4]], dtype=complex)
a4

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

###**itemsize**

O tamanho em bytes de cada elemento do array

In [ ]:
a1 = np.array([[1,2,3]])

a1.itemsize

8

##**Operações com arrays**

###**sin**

Seno

In [ ]:
a1 = np.sin(0)
a1

0.0

In [ ]:
a2 = np.sin(1)
a2

0.8414709848078965

In [ ]:
a3 = np.sin(90)
a3

0.8939966636005579

###**cos**

Cosseno

In [ ]:
a1 = np.cos(0)
a1

1.0

In [ ]:
a2 = np.cos(1)
a2

0.5403023058681398

In [ ]:
a3 = np.cos(180)
a3

-0.5984600690578581

###**exp**

Exponencial

In [ ]:
a1 = np.exp(0)
a1

1.0

###**sqrt**

Raiz

In [ ]:
a1 = np.sqrt(25)
a1

5.0

In [ ]:
a2 = np.sqrt(10)
a2

3.1622776601683795

###**pi**

Valor de pi

In [ ]:
a1 = np.pi
a1

3.141592653589793

###**nan**

Similar ao None, mas só que retorna um dado do tipo float 

In [ ]:
a1 = np.nan
a1

nan

In [ ]:
type(a1)

float

In [ ]:
aux = None
type(aux)

NoneType

###**inf**

Infinito

In [ ]:
a1 = np.inf
a1

inf

In [ ]:
type(a1)

float

###**+**

Adição de arrays

In [ ]:
a1 = np.array([[1,2,3]])
a1

array([[1, 2, 3]])

In [ ]:
a2 = np.array([[3,4,5]])
a2

array([[3, 4, 5]])

In [ ]:
a1 + a2

array([[4, 6, 8]])

In [ ]:
a1 + 2

array([[3, 4, 5]])

In [ ]:
a2 + 2

array([[5, 6, 7]])

> **OBS:** cuidado, pois essas operações não existem na matemática!

###**-**

Subtração de arrays

In [ ]:
a1 = np.array([[1,2,3]])
a1

array([[1, 2, 3]])

In [ ]:
a2 = np.array([[4,5,6]])
a2

array([[4, 5, 6]])

In [ ]:
a2 - a1

array([[3, 3, 3]])

In [ ]:
a1 - a2

array([[-3, -3, -3]])

In [ ]:
a1 - 10

array([[-9, -8, -7]])

In [ ]:
a2 - 1

array([[3, 4, 5]])

> **OBS:** cuidado, pois essas operações não existem na matemática!

###*

Multiplicação de arrays

In [ ]:
a1 = np.array([[1,2,3]])
a1

array([[1, 2, 3]])

In [ ]:
a1.shape

(1, 3)

In [ ]:
a2 = np.array([[4,5,6]])
a2

array([[4, 5, 6]])

In [ ]:
a2.shape

(1, 3)

In [ ]:
a1 * 5

array([[ 5, 10, 15]])

In [ ]:
a2 * 2

array([[ 8, 10, 12]])

In [ ]:
a1 * a2

array([[ 4, 10, 18]])

> **OBS:** cuidado, pois essa operação não pode ser feita de qualquer modo na matemática como numpy considera!

###**/**

Divisão de arrays

In [ ]:
a1 = np.array([[2,4,6]])
a1

array([[2, 4, 6]])

In [ ]:
a2 = np.array([[4,8,12]])
a2

array([[ 4,  8, 12]])

In [ ]:
a2 / a1

array([[2., 2., 2.]])

In [ ]:
a2 / 5

array([[0.8, 1.6, 2.4]])

In [ ]:
a1 / 2

array([[1., 2., 3.]])

In [ ]:
a2 / 4

array([[1., 2., 3.]])

###**dot**

Multiplicação matricial

In [ ]:
#MATRIZ 1X3 ---> 1 LINHA , 3 COLUNAS

a1 = np.array([[1,2,3]])
a1

#a1.shape

array([[1, 2, 3]])

In [ ]:
#MATRIZ 3X1 ---> 3 LINHAS , 1 COLUNA

a2 = np.array([4,5,6])
a2

a2.shape

(3,)

In [ ]:
a1.dot(a2)

array([32])

##**Criação de arrays**

###**zeros**

Constrói um array composto por 0

In [ ]:
a1 = np.zeros(100)
a1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

###**ones**

Constrói um array composto por 1

In [ ]:
a1 = np.ones(20)
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
a2 = np.ones(10)*9.99
a2

array([9.99, 9.99, 9.99, 9.99, 9.99, 9.99, 9.99, 9.99, 9.99, 9.99])

###**eye**

Monta uma matriz identidade

In [ ]:
a1 = np.eye(10)
a1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
a2 = np.eye(5)*np.pi
a2

array([[3.14159265, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 3.14159265, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 3.14159265, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 3.14159265, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 3.14159265]])

###**arange**

Cria uma array a partir das informações inseridas, como: início, fim e passo

In [ ]:
a1 = np.arange(1,5,0.5)
a1

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
a2 = np.arange(1,10,2)
a2

array([1, 3, 5, 7, 9])

In [ ]:
a3 = np.arange(10)

#início = 0
#passo = 1

a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a4 = np.arange(100)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a5 = np.array([5,6,7,8,9])
a6 = np.arange(5)

print(a5)
print(a6)

a5 - a6

[5 6 7 8 9]
[0 1 2 3 4]


array([5, 5, 5, 5, 5])

###**linspace**

Cria uma array a partir das informações inseridas, como: início, fim e quantidade

In [ ]:
a1 = np.linspace(1,5,7)
a1

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [ ]:
a2 = np.linspace(1,10,12)
a2

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [ ]:
a2.size

12

In [ ]:
a1.size

7

In [ ]:
a3 = np.linspace(0,np.pi,3)
a3

array([0.        , 1.57079633, 3.14159265])

###**reshape**

Retorna um array com o shape indicado

In [ ]:
a1 = np.zeros(8)
a1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a1.shape

(8,)

In [ ]:
a1 = a1.reshape(4,2)
a1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a1.shape

(4, 2)

###**resize**

Modificado o shape do array em que está sendo aplicado

In [ ]:
a1 = np.ones(10)
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a1.size

10

In [ ]:
a1.resize(2,5)
a1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###**vstack**

Adiciona elementos de um ou mais array

In [ ]:
a1 = np.zeros(5)
a1

array([0., 0., 0., 0., 0.])

In [ ]:
a2 = np.ones(5)
a2

array([1., 1., 1., 1., 1.])

In [ ]:
a3 = np.vstack((a1,a2))
a3

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a4 = np.hstack((a1,a2))
a4

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

##**Métodos matemáticos**

###**max**

Retorna o valor máximo

In [ ]:
a1 = np.arange(6).reshape(2,3)
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a1.max()

5

In [ ]:
a1[1][0] = 20

print(a1)

a1.max()

[[ 0  1  2]
 [20  4  5]]


20

###**min**

Retorna o valor mínimo

In [ ]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2.min()

0

In [ ]:
a2[0][0] = 10
a2[2][3] = -1

a2.min()

-1

In [ ]:
a2

array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, -1]])

###**argmax**

Retorna o índice do valor máximo

In [ ]:
a1 = np.arange(10).reshape(2,5)
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a1.argmax()

9

###**argmin**

Retorna o índice do valor mínimo

In [ ]:
a2 = np.arange(20).reshape(4,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a2[3][4] = -1

a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, -1]])

In [ ]:
a2.argmin()

19

In [ ]:
a2[0][0] = 20
a2.argmin()

19

###**sum**

Retorna a soma

In [ ]:
a1 = np.arange(10).reshape(2,5)

print(a1)

a1.sum()

[[0 1 2 3 4]
 [5 6 7 8 9]]


45

In [ ]:
a2 = np.arange(6).reshape(2,3)

print(a2)

a2.sum()

[[0 1 2]
 [3 4 5]]


15

###**mean**

Retorna a média

In [ ]:
a1 = np.arange(10).reshape(2,5)

print(a1)

a1.mean()

[[0 1 2 3 4]
 [5 6 7 8 9]]


4.5

In [ ]:
a2 = np.arange(6).reshape(2,3)

print(a2)

a2.mean()

[[0 1 2]
 [3 4 5]]


2.5

###**std**

Retorna o desvio padrão

In [ ]:
a1 = np.arange(10).reshape(2,5)

print(a1)

a1.std()

[[0 1 2 3 4]
 [5 6 7 8 9]]


2.8722813232690143

In [ ]:
a2 = np.arange(6).reshape(2,3)

print(a2)

a2.std()

[[0 1 2]
 [3 4 5]]


1.707825127659933

##**Índices e Fatias**

In [ ]:
a = np.arange(20)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

###**[i]**


In [ ]:
a[10]

100

###**[:i]**

In [ ]:
a[:10]

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

###**[i:]**

In [ ]:
a[10:]

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361])

###**[i1:i2]**

In [ ]:
a[2:13]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

###**[::i]**

In [ ]:
a[::2]

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

###**[::-1]**

In [ ]:
a[::-1]

array([361, 324, 289, 256, 225, 196, 169, 144, 121, 100,  81,  64,  49,
        36,  25,  16,   9,   4,   1,   0])

###**[i1:i2:i3]**

In [ ]:
a[2:14:2]

array([  4,  16,  36,  64, 100, 144])

###**[i,j]**

In [ ]:
a = np.arange(20).reshape(2,10)**2
a

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196, 225, 256, 289, 324, 361]])

In [ ]:
a[1,8]

324

In [ ]:
a[0,5]

25

###**[i,i1:i2]**

In [ ]:
a[0,2:7]

array([ 4,  9, 16, 25, 36])

In [ ]:
a[1:3,9]

array([361])